FROM python

RUN mkdir /service

COPY protobufs/ /service/protobufs/
COPY marketplace/*.py marketplace/templates marketplace/requirements.txt /service/marketplace/
#COPY marketplace/ /service/marketplace/

WORKDIR /service/marketplace

RUN python -m pip install --upgrade pip
RUN python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. \
           --grpc_python_out=. ../protobufs/recommendations.proto

EXPOSE 5000
ENV FLASK_APP=marketplace.py
ENTRYPOINT [ "flask", "run", "--host=0.0.0.0" ]
