FROM python

RUN mkdir /service
COPY protobufs/ /service/protobufs/

COPY recommendations/*.py recommendations/requirements.txt /service/recommendations/
#COPY recommendations/ /service/recommendations/

WORKDIR /service/recommendations

RUN python -m pip install --upgrade pip
RUN python -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. \
           --grpc_python_out=. ../protobufs/recommendations.proto

EXPOSE 50051
ENTRYPOINT [ "python", "recommendations.py" ]
